In [31]:
import numpy as np
from numpy import linalg

In [17]:
n = int(input())

In [22]:
result = np.arange(n, -1, -1)
result

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
np.diag(result)

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [27]:
diag_sum = np.sum(result)
diag_sum


45

In [32]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [34]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [37]:
def cosine(a, b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """

    # длины векторов
    aLength = np.linalg.norm(a)
    bLength = np.linalg.norm(b)

    return np.dot(a, b) / (aLength * bLength)


In [72]:
cos_dict = dict(enumerate(cosine(next_user_stats, i) for i in users_stats))
nearest_client = int(''.join(map(str,([k for k, v in c.items() if v == max(c.values())]))))
nearest_client

7